
elements = [
    # "isBayCedarA1",
    # "isBeach",
    # "isCoastline",
    # "isCoral",
    # "isDunesA",
    # "isDunesB",
    # "isGardeniaA",
    # "isHibiscus",
    # "isHibiscusYoung",
    # "isIronwoodA1",
    # "isIronwoodB",
    # "isKava",
    # "isLavaRocks",
    # "isMountainA",
    # "isMountainB",
    # "isNaupakaA",
    # "isPalmDead",
    # "isPalmRig",
    # "isPandanusA",
    # "osOcean",

    # "isTestPlams",
    # "isMountainAForTest",
    # "isBuilding",
    # "isLucy"
    # "iscity"
    # "desk_Patio",
    # "desk",
    # "desk2",
    # "chair_Patio",
    # "leaves1",
    # "chair3",
    # "chair2",
    # "chair1",
    # "sgfloor",
    # "umbrella",
    # "747",
    # "Airbus_A320Neo",
    # "Airliner",
    # "apfloor",

    # "ARETHEUSE",
    # "AMPHITRITE",
    # "ARRIA",
    # "SEINE",
    # "PHILOPOEMEN",
    # "MELEAGRE",
    # "LOIRE",
    # "Fountain_Mesh"
    # "RENOMME",
    "CHEVAL_MARLY",
    # "resfloor",

    # "building1",
    # "building2",
]